using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TecnoFisc.Sped.Core.SourceGenerators;

/// <summary>
/// Gera, em tempo de compilação, a classe <c>CatalogoSpedGerado</c> de cada projeto que declara
/// registros decorados com <c>[RegistroSped]</c>. Substitui o scan reflexivo de
/// <c>CatalogoBuilder.BuildFromAssembly</c> por um dicionário populado estaticamente — elimina
/// a varredura de <c>Assembly.GetTypes()</c> e a leitura de atributos via reflexão na
/// inicialização do parser/gerador. Os metadados de campos continuam sendo extraídos via
/// helper público do <c>CatalogoBuilder</c> uma única vez na construção do catálogo (delegates
/// compilados ficam em cache, fora da hot path).
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RegistroSpedCatalogoGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "TecnoFisc.Sped.Core.Atributos.RegistroSpedAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<InfoRegistro> registros = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (n, _) => n is ClassDeclarationSyntax,
                transform: static (ctx, _) => ExtrairInfoRegistro(ctx))
            .Where(static info => info.HasValue)
            .Select(static (info, _) => info!.Value);

        IncrementalValueProvider<ImmutableArray<InfoRegistro>> coletados = registros.Collect();
        IncrementalValueProvider<string> assemblyName = context.CompilationProvider
            .Select(static (c, _) => c.AssemblyName ?? "Generated");

        var combinado = coletados.Combine(assemblyName);

        context.RegisterSourceOutput(combinado, static (spc, dados) =>
        {
            var (lista, asmName) = dados;
            if (lista.IsDefaultOrEmpty)
                return;

            string fonte = GerarCatalogo(lista, asmName);
            spc.AddSource("CatalogoSpedGerado.g.cs", SourceText.From(fonte, Encoding.UTF8));
        });
    }

    private static InfoRegistro? ExtrairInfoRegistro(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol tipo)
            return null;
        if (tipo.IsAbstract)
            return null;

        AttributeData? atributo = ctx.Attributes.FirstOrDefault();
        if (atributo is null)
            return null;

        string? codigo = null;
        string? bloco = null;
        int nivel = 0;
        foreach (KeyValuePair<string, TypedConstant> arg in atributo.NamedArguments)
        {
            switch (arg.Key)
            {
                case "Codigo":
                    codigo = arg.Value.Value as string;
                    break;
                case "Nivel":
                    nivel = arg.Value.Value is int n ? n : 0;
                    break;
                case "Bloco":
                    bloco = arg.Value.Value as string;
                    break;
            }
        }

        if (string.IsNullOrEmpty(codigo) || string.IsNullOrEmpty(bloco))
            return null;

        string tipoFq = tipo.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new InfoRegistro(tipoFq, codigo!, nivel, bloco!);
    }

    private static string GerarCatalogo(ImmutableArray<InfoRegistro> registros, string assemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using TecnoFisc.Sped.Core.Catalogo;");
        sb.AppendLine();
        sb.AppendLine("namespace " + assemblyName + ".Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Catálogo de registros SPED gerado em tempo de compilação pelo");
        sb.AppendLine("/// <c>TecnoFisc.Sped.Core.SourceGenerators</c>. Cada entrada do dicionário");
        sb.AppendLine("/// foi descoberta a partir das classes decoradas com <c>[RegistroSped]</c>");
        sb.AppendLine("/// neste assembly — sem <c>Assembly.GetTypes()</c> em runtime.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class CatalogoSpedGerado : CatalogoSpedBase");
        sb.AppendLine("{");
        sb.AppendLine("    public CatalogoSpedGerado() : base(BuildRegistros()) { }");
        sb.AppendLine();
        sb.AppendLine("    private static Dictionary<string, MetadadosRegistro> BuildRegistros()");
        sb.AppendLine("    {");
        sb.Append("        var registros = new Dictionary<string, MetadadosRegistro>(");
        sb.Append(registros.Length.ToString(System.Globalization.CultureInfo.InvariantCulture));
        sb.AppendLine(", StringComparer.Ordinal);");

        IOrderedEnumerable<InfoRegistro> ordenados =
            registros.OrderBy(static r => r.Codigo, System.StringComparer.Ordinal);
        foreach (InfoRegistro r in ordenados)
        {
            sb.Append("        registros.Add(\"");
            sb.Append(r.Codigo);
            sb.Append("\", CatalogoBuilder.ConstruirMetadadosDoTipo(typeof(");
            sb.Append(r.TipoFullyQualified);
            sb.Append("), \"");
            sb.Append(r.Codigo);
            sb.Append("\", ");
            sb.Append(r.Nivel.ToString(System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(", \"");
            sb.Append(r.Bloco);
            sb.Append("\", static () => new ");
            sb.Append(r.TipoFullyQualified);
            sb.AppendLine("()));");
        }

        sb.AppendLine("        return registros;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private readonly record struct InfoRegistro(
        string TipoFullyQualified,
        string Codigo,
        int Nivel,
        string Bloco);
}
